[target.'cfg(target_os = "macos")']
rustflags = [
  "-C",
  "link-arg=-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/vecLib.framework/Headers",
  "-C",
  "link-arg=-lblas",
  "-C",
  "link-arg=-undefined",
  "-C",
  "link-arg=dynamic_lookup",
  "-C",
  "link-arg=-DACCELERATE_NEW_LAPACK",
]
