[package]
name = "elixirml_nifs"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "elixirml_nifs"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.147"
rand = "0.8.5"
rand_distr = "0.4.3"
rustler = { version = "0.29.1", features = ["nif_version_2_17"] }
